version: 2  # 必须加这一行，修复你的报错

project_name: multi-platform-products

release:
  draft: false
  prerelease: false

# 因为 fyne-cross 已生成压缩包，这里让 Goreleaser 只负责上传 artifacts/ 中的文件
# 不需要 builds 部分（fyne-cross 已经处理）

archives:
  format_overrides:
    - goos: windows
      format: zip
  name_template: "multi-platform-products-{{ .Os }}-{{ .Arch }}-{{ .Tag }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  skip: true  # 如果不需要自动生成 changelog，可以跳过